[package]
name = "bevy_audio_core"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]

std = []

[dependencies]
bevy_ecs = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_platform = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_log = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_app = { git = "https://github.com/bevyengine/bevy.git", default-features = false }

thiserror = { version = "1", default-features = false }
rtrb = { version = "0.3", default-features = false }
